# Generated by Django 5.2.9 on 2025-12-14 07:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypertension', '0005_alter_bloodpressurereading_options_watchsync_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchBloodPressure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('systolic', models.IntegerField()),
                ('diastolic', models.IntegerField()),
                ('pulse', models.PositiveIntegerField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('raw', models.JSONField(blank=True, null=True)),
                ('watch_sync', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_readings', to='hypertension.watchsync')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
