# Generated by Django 5.2.9 on 2025-12-15 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypertension', '0008_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hypertension.device'),
        ),
        migrations.AddField(
            model_name='alert',
            name='sodium_total',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='threshold_percent',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
