# Generated by Django 5.2.9 on 2025-12-10 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypertension', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodPressureReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('systolic', models.IntegerField()),
                ('diastolic', models.IntegerField()),
                ('pulse', models.PositiveIntegerField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='BloodPressure',
        ),
    ]
